In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:

import numpy as np
arr = np.zeros([2,3])
print(arr)
arr1 = np.ones([3,3])
print(arr1)
arr2 = np.full([2,2],6)
print(arr2)
arr3 = np.empty([1,2])
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6 6]
 [6 6]]
[[1.02696246e-311 0.00000000e+000]]


In [1]:
import pandas as ps
arr=ps.array([1,2,3])
print(arr)

<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int64
